from typing import Any, Protocol
from uuid import UUID


class Repository(Protocol):
    async def profile_for_user(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def memberships_for_user(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def organizations_for_user(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def schemas_for_user(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def schema_for_user(self, schema_id: UUID) -> dict[str, Any] | None: ...
    async def prescription_for_user(self, prescription_id: UUID) -> dict[str, Any] | None: ...
    async def create_schema(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_schema(self, schema_id: UUID, data: dict[str, Any]) -> dict[str, Any]: ...
    async def activate_schema(self, schema_id: UUID) -> dict[str, Any]: ...
    async def delete_schema(self, schema_id: UUID) -> None: ...
    async def fields_for_user(self, prescription_id: UUID) -> list[dict[str, Any]]: ...
    async def correct_field(
        self, field_id: UUID, value: Any, reason: str | None
    ) -> dict[str, Any]: ...
    async def approve_snapshot(
        self, prescription_id: UUID, snapshot: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def approved_version(self, prescription_id: UUID) -> dict[str, Any] | None: ...
    async def add_array_item(
        self, prescription_id: UUID, array_path: str, values: dict[str, Any]
    ) -> list[dict[str, Any]]: ...
    async def remove_array_item(
        self, prescription_id: UUID, array_item_id: str
    ) -> list[dict[str, Any]]: ...
    async def list_prescriptions(
        self,
        organization_id: UUID,
        limit: int,
        created_before: str | None,
    ) -> list[dict[str, Any]]: ...
    async def organization_metrics(self, organization_id: UUID) -> dict[str, Any]: ...
    async def corrections_for_prescriptions(
        self, prescription_ids: list[UUID]
    ) -> list[dict[str, Any]]: ...
    async def approval_workflow(self, organization_id: UUID) -> dict[str, Any] | None: ...
    async def approval_steps(self, prescription_id: UUID) -> list[dict[str, Any]]: ...
    async def record_approval_step(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def assert_membership(
        self, user_id: UUID, organization_id: UUID, roles: set[str] | None = None
    ) -> dict[str, Any]: ...
