from typing import Any, Protocol
from uuid import UUID


class ProcessingRepository(Protocol):
    async def find_duplicate(self, organization_id: UUID, sha256: str) -> dict[str, Any] | None: ...
    async def create_prescription(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_prescription(self, prescription_id: UUID, data: dict[str, Any]) -> None: ...
    async def get_prescription(
        self, prescription_id: UUID, organization_id: UUID
    ) -> dict[str, Any] | None: ...
    async def create_page(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_page(self, page_id: UUID, data: dict[str, Any]) -> None: ...
    async def pages(self, prescription_id: UUID) -> list[dict[str, Any]]: ...
    async def create_job(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def finish_job(self, job_id: UUID, data: dict[str, Any]) -> None: ...
    async def jobs(self, prescription_id: UUID) -> list[dict[str, Any]]: ...
    async def create_ocr_result(
        self, result: dict[str, Any], tokens: list[dict[str, Any]]
    ) -> dict[str, Any]: ...
    async def ocr_results(
        self, prescription_id: UUID, include_tokens: bool = True
    ) -> list[dict[str, Any]]: ...
    async def schema(self, schema_id: UUID) -> dict[str, Any] | None: ...
    async def create_extraction_run(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def create_fields(self, fields: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    async def delete_fields(self, prescription_id: UUID) -> None: ...
    async def fields(self, prescription_id: UUID) -> list[dict[str, Any]]: ...
    async def diagnostics(
        self, organization_id: UUID, limit: int
    ) -> list[dict[str, Any]]: ...
